services.service_endpoint.*:
  type: config_entity
  label: 'Service Endpoint config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'Uuid'
    endpoint:
      type: string
      label: 'Endpoint'
